package com.example.app_diabetes


object Frases {
    val frases = listOf(
        "Hoy es un buen día para cuidarte",
        "Tú puedes con todo",
        "Cada registro es un paso",
        "Sigue así, vas genial",
        "Tu salud lo vale",
        "Vales un montón",
        "Cada pequeño esfuerzo cuenta",
        "Estás haciendo un gran trabajo",
        "Tu constancia es admirable",
        "No te detengas, vas muy bien",
        "La salud es tu mejor inversión",
        "Confía en ti y en tu proceso",
        "Todo esfuerzo tiene su recompensa",
        "Estás más fuerte de lo que crees",
        "Cuidarte es un acto de amor",
        "Sigue avanzando, lo estás haciendo genial",
        "El camino se hace paso a paso",
        "Pequeños logros crean grandes cambios",
        "Tu bienestar es una prioridad",
        "Estás haciendo lo correcto",
        "Eres capaz de lograrlo",
        "Hoy elegiste cuidarte, eso es valiente",
        "Tu esfuerzo no pasa desapercibido",
        "Sigue con esa actitud positiva",
        "Cuidarte también es quererte",
        "Estás haciendo lo mejor para ti",
        "Paso a paso se llega lejos",
        "No subestimes tu compromiso",
        "Cada día es una nueva oportunidad",
        "Tu salud agradece cada registro",
        "Estás marcando la diferencia en tu vida",
        "Sigue apostando por ti",
        "Tu constancia inspira",
        "Eres un ejemplo de fortaleza",
        "Lo estás haciendo muy bien",
        "Cuida tu cuerpo, es el único que tienes",
        "Hoy lo has hecho genial",
        "Gracias por cuidarte",
        "No te rindas, estás avanzando",
        "Confía en tu esfuerzo diario",
        "Estás siendo muy valiente",
        "Eres más fuerte de lo que imaginas",
        "Estás priorizando lo importante",
        "Sigue cultivando tu salud",
        "Un registro más es un paso más",
        "Hoy puede ser mejor que ayer",
        "Mereces sentirte bien",
        "Tu dedicación da frutos",
        "Estás en el camino correcto",
        "Hazlo por ti, tú lo vales"
    )
}
